target 'Swig', :exclusive => true do
  pod "Swig", :path => "../"
  pod 'DESCrypt', :git => 'https://github.com/MaximKeegan/DESCrypt.git'
  pod 'IQKeyboardManager'
  
end

target 'Swig-Swift', :exclusive => true do
  pod "Swig", :path => "../"
end

target 'Swig-Pod', :exclusive => true do
  pod 'AFNetworking/Reachability', '~> 2.3'
  pod 'libextobjc', '~> 0.4'
  pod 'pjsip-ios'
  pod 'CocoaLumberjack', '2.0.0-rc'
end

target 'Swig-PodTests', :exclusive => true do
  pod 'pjsip-ios'
end
